wrists/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'users#current_user_home'

  resources :items, except: [:index, :show]

  resources :lists

  resources :users, only: [:show, :create, :new]

end

wrists/app/models/ability.rb
class Ability
    include CanCan::Ability

    def initialize(user)
      user ||= User.new
      if user.role? :admin
        can :manage, :all
      



      elsif user.persisted?
        
        can :read, List do |list|
            list.try(:user) == user
        end

        can :create, List

        can :destroy, List do |list|
            list.try(:user) == user
        end

        can :update, List do |list|
            list.try(:user) == user
        end


# ***********************************************************
        cannot :read, Item

        can :create, Item

        cannot :update, Item

        can :destroy, Item do |item|
            item.list.try(:user) == user
        end

        # ***********************************************************
        can :manage, User do |u|
            u.id == user.id
        end
        

        
      else
        cannot :destroy, List
      end
    end
end

wrists/app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list
end

wrists/app/models/list.rb
class List < ActiveRecord::Base
  has_many :items
  belongs_to :user
end

wrists/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :lists

  def role?(role_to_compare)
    self.role.to_s == role_to_compare.to_s
  end

  
end

wrists/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

wrists/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  load_and_authorize_resource
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  # def index
  #   @items = Item.all
  # end

  # GET /items/1
  # GET /items/1.json
  # def show
  # end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
 def create
   @item = Item.new(item_params)
   @item.save
   @list = List.where(id: @item.list_id).map {|list| list}
   redirect_to list_path(@list)
 end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    # respond_to do |format|
    #   format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
    redirect_to lists_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :list_id, :status)
    end
end

wrists/app/controllers/lists_controller.rb
class ListsController < ApplicationController
  load_and_authorize_resource
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  respond_to :html
  # GET /lists
  # GET /lists.json
  # def index
  #   @lists = List.all
  # end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @items = @list.items
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    # respond_to do |format|
    #   format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
    redirect_to current_user
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:user_id, :title)
    end
end

wrists/app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  # def index
  #   @users = User.all
  # end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  def current_user_home
    redirect_to current_user
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  # def edit
  # end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  # def update
  #   respond_to do |format|
  #     if @user.update(user_params)
  #       format.html { redirect_to @user, notice: 'User was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @user }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /users/1
  # DELETE /users/1.json
  # def destroy
  #   @user.destroy
  #   respond_to do |format|
  #     format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:role, :username)
    end
end

wrists/app/helpers/application_helper.rb
module ApplicationHelper
end

wrists/app/helpers/items_helper.rb
module ItemsHelper
end

wrists/app/helpers/lists_helper.rb
module ListsHelper
end

wrists/app/helpers/users_helper.rb
module UsersHelper
end

wrists/app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :list_id %><br>
    <%= f.number_field :list_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

wrists/app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

wrists/app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

wrists/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wrists</title>
  <link href='//fonts.googleapis.com/css?family=Playball' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



    <header class="navigation" role="banner">
      <div class="navigation-wrapper">
        <h1>
          <%= link_to 'Wrangler ToDo', current_user, :id => "cursive_logo", :class=>"logo"  %>
        </h1>
        <a href="javascript:void(0)" class="navigation-menu-button" id="js-mobile-menu">MENU</a>
        <nav role="navigation">
          <ul id="js-navigation-menu" class="navigation-menu show">
              <% if current_user %>
              <li class="nav-link"> 
               <%= link_to current_user.email, current_user %> 
             </li>
             <li class="nav-link">
               <%= link_to "Log out", destroy_user_session_path, method: :delete %>
             </li>
                

              <% else %>
              <li class="nav-link">
                <%= link_to "Sign In", new_user_session_path %>
              </li>
              <li class="nav-link">
                <%= link_to "Register", new_user_registration_path %>
              </li>
              <% end %>
            
          </ul>
        </nav>
      </div>
    </header>

<!--     <p class="notice"><%= notice %></p> -->
    <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

wrists/app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="field">
    <%= f.text_field :title, :placeholder => 'e.g. Super duper list' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

wrists/app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form' %>

<%= link_to 'Back', @list %> 

wrists/app/views/lists/new.html.erb
<h1>Create a new list</h1>

<%= render 'form' %>

wrists/app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong><%= @list.title %></strong>
  <%= link_to 'Edit', edit_list_path(@list) %>
</p>




<%= form_for Item.new do |item_form|%>
  <%= item_form.text_field :name, placeholder: 'Add stuff' %>

<%= item_form.hidden_field :list_id, :value => @list.id %>
<div class="actions">
  <%= item_form.submit %>
</div>
<% end %>

<table class="table-minimal">
  <thead>
    <tr>
      <th>To Do  </th>
    </tr>
  </thead>
  <tbody id = "entries">
    <% @list.items.each do |item| %>
    <tr>
      <td class = 'item_name'> <%= item.name %></td>
    </tr>
    <% end %>
  </tbody>
</table>





<br>
<br>

wrists/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table-minimal">
  <thead>
    <th><%= link_to 'Create a new list', new_list_path  %></th>
  </thead>

  <tbody>
    <% @user.lists.each do |list| %>
    <tr> 
      <td><%= link_to list.title, list, method: :get %></td>
      <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>


</table>